// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqvuiegjmdkvcrpuevxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxdnVpZWdqbWRrdmNycHVldnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzUzMDcsImV4cCI6MjA3MzYxMTMwN30.K0aqStpnqO4xbFjTva8nkU-qkWOATmrcLY39Mw8Irkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});